server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: fapi_route
          uri: http://localhost:8123
          predicates:
#            - Path=/api/{api_url}
            - Path=/api/hello/user

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
